variables:
  Solution: FluentWPF.sln

before_script:
  - "echo off"
  - 'call "%VS150COMNTOOLS%vsdevcmd.bat"'
  # output environment variables (usefull for debugging, propably not what you want to do if your ci server is public)
  - echo.
  - set
  - echo.

stages:
  - build

build:
  stage: build
  script:
    - nuget restore
    - echo building...
    - 'msbuild.exe "%Solution%"'
  except:
    - tags